WITH TABELA AS ( 
	SELECT
		R.CODLOJ Filial,
		P.EMIPED,
		X.NUMPEDP AS PEDIDO,
		DATEADD(DAY,ISNULL(C.PMRM,0),R.DTHCAD) DTHPREV,
		X.CODCLI,
		C.FANTASIA  AS Fornecedor,
		R.NUMNOT,
		X.QTDSTK*1.00   AS QTDSTK,
		X.QTDADE,
		E.ZERADOS*1.00  AS ZERADOS,
		CASE WHEN CN.SEQIT IS NULL THEN 'NAO' ELSE 'SIM' END AS CONF,
		CASE WHEN AP.SEQIT IS NULL THEN 'NAO' ELSE 'SIM' END AS ARMAZ,
		CASE WHEN FI.SEQIT IS NULL THEN '___' ELSE 'SIM' END AS FIS,
		CASE WHEN CO.SEQIT IS NULL THEN '___' ELSE 'SIM' END AS COM,
		(SELECT TOP 1 R1.OBSREC FROM JACSYSDB.dbo.ITEMNXP AS R1 WHERE R1.NFEID=R.NFEID AND R1.SEQIT LIKE '%[0-9]%') AS OBSREC,
		X.OBS AS OBSPED , X.CODNAT, X.NOME NATUR,
		R.NFEID,
		CASE WHEN REQRC.NUMREQ IS NULL THEN 0 ELSE 1 END + CASE WHEN REQNC.NUMREQ IS NULL THEN 0 ELSE 1 END AS NFS ,
		ISNULL(REQRC.NUMREQ,REQNC.NUMREQ) AS NUMREQ, ISNULL(REQRC.TIPOREQ,REQNC.TIPOREQ) AS TIPOREQ
	FROM JACSYSDB.dbo.ITEMNXP R
		OUTER APPLY(
			SELECT T.QTDSTK, T.NUMPEDP,T.QTDADE,T.CODCLI, PC.OBS, PC.CODNAT,N.NOME
			FROM (SELECT TOP 1 COUNT(DISTINCT(X.CODSTK)) QTDSTK, MAX(X.NUMPEDP) NUMPEDP, SUM(X.QTDADE) QTDADE, MIN(X.CODCLI) CODCLI
					FROM JACSYSDB.dbo.ITEMNXP AS X WHERE X.NFEID=R.NFEID AND X.MOVSTK='E' ) AS T
						LEFT JOIN JACSYSDB.dbo.REQRPC AS PC ON (PC.NUMREQ=T.NUMPEDP)
						LEFT JOIN JACSYSDB.dbo.NATOPR AS N ON (N.CODNAT=PC.CODNAT)
			) AS X
		LEFT JOIN JACSYSDB.dbo.CLIENTES C ON (C.CODCLI=X.CODCLI)
		OUTER APPLY(SELECT TOP 1 MIN(PC.DATEMI) EMIPED FROM JACSYSDB.dbo.PEDHIS PC WHERE PC.NUMREQ=X.NUMPEDP) AS P
		OUTER APPLY(
			SELECT COUNT(DISTINCT(ES.CODSTK)) ZERADOS
				FROM JACSYSDB.dbo.ITEMSTK ES
					LEFT JOIN JACSYSDB.dbo.ITEMNXP N ON N.CODSTK=ES.CODSTK
				WHERE (ES.TIPOSTK='P') AND (ES.ESTOQUE=0) AND (ES.CLABCFAT IN ('A','B','C')) AND N.NFEID=R.NFEID AND N.MOVSTK='E' ) AS E
		OUTER APPLY(SELECT TOP 1 CNF.SEQIT FROM JACSYSDB.dbo.ITEMNXP CNF WHERE CNF.NFEID=R.NFEID AND CNF.SEQIT='CNF') AS CN
		OUTER APPLY(SELECT TOP 1 APE.SEQIT FROM JACSYSDB.dbo.ITEMNXP APE WHERE APE.NFEID=R.NFEID AND APE.SEQIT='APE') AS AP
		OUTER APPLY(SELECT TOP 1 CNF.SEQIT FROM JACSYSDB.dbo.ITEMNXP CNF WHERE CNF.NFEID=R.NFEID AND CNF.SEQIT='FIS') AS FI
		OUTER APPLY(SELECT TOP 1 CNF.SEQIT FROM JACSYSDB.dbo.ITEMNXP CNF WHERE CNF.NFEID=R.NFEID AND CNF.SEQIT='COM') AS CO
		OUTER APPLY(SELECT TOP 1 RC.NUMREQ, RC.TIPOREQ FROM JACSYSDB.dbo.REQCOM RC WHERE (RC.TIPOREQ IN ('RC','NE','TS','TE')) AND (RC.NFEID = R.NFEID) ) AS REQRC
		OUTER APPLY(SELECT TOP 1 NC.NUMREQ, NC.TIPOREQ+'(C)' AS TIPOREQ FROM JACSYSDB.dbo.REQNFC NC WHERE (NC.TIPOREQ IN ('RC','NE','MC')) AND (NC.NFEID = R.NFEID) ) AS REQNC

	WHERE (ISNULL(LEN(R.NFEID),'0')<>'0')
		AND (R.SEQIT='REC')
		AND (R.DTHCAD <= {TS '2025-05-21 23:59:59'})
		AND (X.CODCLI NOT IN ('320864', '300001') )
)
SELECT
	T.Filial,
	T.EMIPED,
	T.DTHPREV,
	T.Pedido,
	T.CODCLI,
	T.Fornecedor,
	T.NUMNOT,
	T.QTDSTK,
	T.ZERADOS,
	CASE WHEN T.QTDSTK > 0 THEN (T.ZERADOS/T.QTDSTK)*100.00 ELSE 0.0 END AS PzeroABC,
	T.CONF,
	T.ARMAZ,
	T.OBSREC,
	T.OBSPED,
	CASE WHEN isnull(T.OBSREC,'') NOT LIKE '%RECEBI%' THEN '3. AGUARDANDO RECEBIMENTO'
	WHEN isnull(T.OBSREC,'')     LIKE '%RECEBI%' THEN '1. AGUARDANDO CONFERÊNCIA'
	WHEN T.CONF = 'CNF'                          THEN '2. AGUARDANDO ARMAZENAGEM'  ELSE '4. Verifique...' END STATUS ,
	FIS,
	COM,
	CODNAT,
	T.NFEID AS Chave,
	T.NUMREQ REQ, T.TIPOREQ TR
	
FROM TABELA T
WHERE (1=1)
	AND (NFS = 0)
	AND (T.ARMAZ  ='NAO')
	
ORDER BY 15 , 10 DESC
