SELECT
	REL.*
	
FROM (
	SELECT
		'Emitida'  Sit,
		 CASE WHEN substring(R.CFOP,1,1) IN ('1','2','3') THEN 'E' ELSE 'S' END AS ENTSAI,
		' ' AS COD_NOTA,
		' ' AS MVA,
		' ' AS COD_IBGE,
		R.DATEMI,
		R.DATSAI,
		R.NUMREQ, 
		R.TIPOREQ,
		 CASE WHEN isnull(LEN(R.CFEID),0)<>0 AND isnull(LEN(R.NFEID),0)= 0 THEN substring(R.CFEID,21,2)
		WHEN isnull(LEN(R.CFEID),0)<>0 AND isnull(LEN(R.NFEID),0)<>0 THEN substring(R.NFEID,21,2)
		WHEN isnull(LEN(R.NFEID),0)<>0 AND isnull(LEN(R.CFEID),0)= 0 THEN substring(R.NFEID,21,2) ELSE R.MODNF END AS Mod,
		CASE WHEN isnull(LEN(R.CFEID),0)<>0 THEN R.CFESTA ELSE R.NFERWS END AS STA,
		R.NFERWS,
		R.CFESTA,
		R.NUMNOT,
		R.NUMNCF,
		CASE WHEN isnull(LEN(R.CFEID),0)<>0 AND isnull(LEN(R.NFEID),0)=0 THEN R.CFEID ELSE R.NFEID END  AS Chave,
		R.NFEPRO,
		R.CODCLI,
		C.NOME,
		C.ENDERECO+', '+C.NUMERO AS ENDER,
		C.BAIRRO,
		C.CIDADE,
		C.UF,
		R.CPFCNPJ,
		R.PESSOA,
		R.TOTGERAL,
		I.SEQIT,
		I.CODSTK,
		I.CODFAB,
		I.CODEAN,
		I.NOME    AS Produto,
		I.CODIPI,
		I.CFOP,
		I.UNIDADE,
		I.QTDADE,
		I.PRCLIQ,
		I.TOTLIQ,
		I.PRCCTB,
		I.CODCST,
		I.ALQICM,
		I.VLRICM,
		I.PRCCTB AS BICMSST,
		I.ALQSBT,
		I.VLRRET,
		I.CSTPIS,
		I.ALQPIS,
		I.VLRPIS,
		I.CSTCOF,
		I.ALQCOF,
		I.VLRCOF,
		I.ALQIPI,
		I.VLRIPI,
		CASE WHEN LEN(LTRIM(ISNULL(R.Portal,''))) = 0 THEN 'Loja' ELSE R.PORTAL END AS Portal,
		R.Prisma,
		CASE WHEN I.TIPOSTK='S' THEN R.NUMNFS ELSE NULL END AS NUMNFS,
		CASE WHEN I.TIPOSTK='S' THEN R.TOTSRV ELSE NULL END AS TOTSRV,
		CASE WHEN I.TIPOSTK='S' THEN R.NFSPRO ELSE NULL END AS NFSPRO,
		ISNULL(I.PRCDAI,0) BSTFCP,
		ISNULL(I.ALQFCP,0) ALQFCP,
		ISNULL(I.VLRFCP,0) VSTFCP,
		ISNULL(I.BICENT,0) BICENT,
		ISNULL(I.AICENT,0) AICENT,
		ISNULL(I.VICENT,0) VICENT,
		ISNULL(I.BSTENT,0) BSTENT,
		ISNULL(I.ALQSBT,0) ALQSBT2,
		ISNULL(I.VSTENT,0) VSTENT,
		ISNULL(I.FRETE,0) FRETE,
		ISNULL(I.SEGURO,0) SEGURO,
		ISNULL(I.ACESSORIA,0) ACESSORIA,
		ISNULL(I.DSCREQ,0) DSCREQ,
		R.NFEDWS 

	FROM REQVDA R
		LEFT JOIN CLIENTES C ON (C.CODCLI=R.CODCLI)
		LEFT JOIN ITEMVDA I ON (I.SID=R.SID)

	WHERE ((LEN(R.NUMNOT)>0) OR (LEN(R.NUMNCF)>0))
		AND (R.DATSAI >= '01-MAY-2025')
		AND (R.DATSAI <= '06-MAY-2025')
		AND (R.TIPONF  = 'I')

	union all

	SELECT
		'Emitida'  Sit,
		 CASE WHEN substring(R.CFOP,1,1) IN ('1','2','3') THEN 'E' ELSE 'S' END AS ENTSAI,
		' ' AS COD_NOTA,
		' ' AS MVA,
		' ' AS COD_IBGE,
		R.DATEMI,
		R.DATSAI,
		R.NUMREQ, 
		R.TIPOREQ,
		 CASE WHEN isnull(LEN(R.CFEID),0)<>0 AND isnull(LEN(R.NFEID),0)= 0 THEN substring(R.CFEID,21,2)
		WHEN isnull(LEN(R.CFEID),0)<>0 AND isnull(LEN(R.NFEID),0)<>0 THEN substring(R.NFEID,21,2)
		WHEN isnull(LEN(R.NFEID),0)<>0 AND isnull(LEN(R.CFEID),0)= 0 THEN substring(R.NFEID,21,2) ELSE R.MODNF END AS Mod,
		CASE WHEN isnull(LEN(R.CFEID),0)<>0 THEN R.CFESTA ELSE R.NFERWS END AS STA,
		R.NFERWS,
		R.CFESTA,
		R.NUMNOT,
		R.NUMNCF,
		CASE WHEN isnull(LEN(R.CFEID),0)<>0 AND isnull(LEN(R.NFEID),0)=0 THEN R.CFEID ELSE R.NFEID END  AS Chave,
		R.NFEPRO,
		R.CODCLI,
		C.NOME,
		C.ENDERECO+', '+C.NUMERO AS ENDER,
		C.BAIRRO,
		C.CIDADE,
		C.UF,
		R.CPFCNPJ,
		R.PESSOA,
		R.TOTGERAL,
		I.SEQIT,
		I.CODSTK,
		I.CODFAB,
		I.CODEAN,
		I.NOME    AS Produto,
		I.CODIPI,
		I.CFOP,
		I.UNIDADE,
		I.QTDADE,
		I.PRCLIQ,
		I.TOTLIQ,
		I.PRCCTB,
		I.CODCST,
		I.ALQICM,
		I.VLRICM,
		I.PRCCTB AS BICMSST,
		I.ALQSBT,
		I.VLRRET,
		I.CSTPIS,
		I.ALQPIS,
		I.VLRPIS,
		I.CSTCOF,
		I.ALQCOF,
		I.VLRCOF,
		I.ALQIPI,
		I.VLRIPI,
		CASE WHEN LEN(LTRIM(ISNULL(R.Portal,''))) = 0 THEN 'Loja' ELSE R.PORTAL END AS Portal,
		R.Prisma,
		CASE WHEN I.TIPOSTK='S' THEN R.NUMNFS ELSE NULL END AS NUMNFS,
		CASE WHEN I.TIPOSTK='S' THEN R.TOTSRV ELSE NULL END AS TOTSRV,
		CASE WHEN I.TIPOSTK='S' THEN R.NFSPRO ELSE NULL END AS NFSPRO,
		ISNULL(I.PRCDAI,0) BSTFCP,
		ISNULL(I.ALQFCP,0) ALQFCP,
		ISNULL(I.VLRFCP,0) VSTFCP,
		ISNULL(I.BICENT,0) BICENT,
		ISNULL(I.AICENT,0) AICENT,
		ISNULL(I.VICENT,0) VICENT,
		ISNULL(I.BSTENT,0) BSTENT,
		ISNULL(I.ALQSBT,0) ALQSBT2,
		ISNULL(I.VSTENT,0) VSTENT,
		ISNULL(I.FRETE,0) FRETE,
		ISNULL(I.SEGURO,0) SEGURO,
		ISNULL(I.ACESSORIA,0) ACESSORIA,
		ISNULL(I.DSCREQ,0) DSCREQ,
		R.NFEDWS 

	FROM REQCOM R
		LEFT JOIN CLIENTES C ON (C.CODCLI=R.CODCLI)
		LEFT JOIN ITEMCOM I ON (I.SID=R.SID)

	WHERE ((LEN(R.NUMNOT)>0) OR (LEN(R.NUMNCF)>0))
		AND (R.DATSAI >= '01-MAY-2025')
		AND (R.DATSAI <= '06-MAY-2025')
		AND (R.TIPONF  = 'I')

	union all

	SELECT
		'Emitida'  Sit,
		 CASE WHEN substring(R.CFOP,1,1) IN ('1','2','3') THEN 'E' ELSE 'S' END AS ENTSAI,
		' ' AS COD_NOTA,
		' ' AS MVA,
		' ' AS COD_IBGE,
		R.DATEMI,
		R.DATSAI,
		R.NUMREQ, 
		R.TIPOREQ+'(C)' AS TIPOREQ,
		 CASE WHEN isnull(LEN(R.CFEID),0)<>0 AND isnull(LEN(R.NFEID),0)= 0 THEN substring(R.CFEID,21,2)
		WHEN isnull(LEN(R.CFEID),0)<>0 AND isnull(LEN(R.NFEID),0)<>0 THEN substring(R.NFEID,21,2)
		WHEN isnull(LEN(R.NFEID),0)<>0 AND isnull(LEN(R.CFEID),0)= 0 THEN substring(R.NFEID,21,2) ELSE R.MODNF END AS Mod,
		CASE WHEN isnull(LEN(R.CFEID),0)<>0 THEN R.CFESTA ELSE R.NFERWS END AS STA,
		R.NFERWS,
		R.CFESTA,
		R.NUMNOT,
		R.NUMNCF,
		CASE WHEN isnull(LEN(R.CFEID),0)<>0 AND isnull(LEN(R.NFEID),0)=0 THEN R.CFEID ELSE R.NFEID END  AS Chave,
		R.NFEPRO,
		R.CODCLI,
		C.NOME,
		C.ENDERECO+', '+C.NUMERO AS ENDER,
		C.BAIRRO,
		C.CIDADE,
		C.UF,
		R.CPFCNPJ,
		R.PESSOA,
		R.TOTGERAL,
		I.SEQIT,
		I.CODSTK,
		I.CODFAB,
		I.CODEAN,
		I.NOME    AS Produto,
		I.CODIPI,
		I.CFOP,
		I.UNIDADE,
		I.QTDADE,
		I.PRCLIQ,
		I.TOTLIQ,
		I.PRCCTB,
		I.CODCST,
		I.ALQICM,
		I.VLRICM,
		I.PRCCTB AS BICMSST,
		I.ALQSBT,
		I.VLRRET,
		I.CSTPIS,
		I.ALQPIS,
		I.VLRPIS,
		I.CSTCOF,
		I.ALQCOF,
		I.VLRCOF,
		I.ALQIPI,
		I.VLRIPI,
		CASE WHEN LEN(LTRIM(ISNULL(R.Portal,''))) = 0 THEN 'Loja' ELSE R.PORTAL END AS Portal,
		R.Prisma,
		CASE WHEN I.TIPOSTK='S' THEN R.NUMNFS ELSE NULL END AS NUMNFS,
		CASE WHEN I.TIPOSTK='S' THEN R.TOTSRV ELSE NULL END AS TOTSRV,
		CASE WHEN I.TIPOSTK='S' THEN R.NFSPRO ELSE NULL END AS NFSPRO,
		ISNULL(I.PRCDAI,0) BSTFCP,
		ISNULL(I.ALQFCP,0) ALQFCP,
		ISNULL(I.VLRFCP,0) VSTFCP,
		ISNULL(I.BICENT,0) BICENT,
		ISNULL(I.AICENT,0) AICENT,
		ISNULL(I.VICENT,0) VICENT,
		ISNULL(I.BSTENT,0) BSTENT,
		ISNULL(I.ALQSBT,0) ALQSBT2,
		ISNULL(I.VSTENT,0) VSTENT,
		ISNULL(I.FRETE,0) FRETE,
		ISNULL(I.SEGURO,0) SEGURO,
		ISNULL(I.ACESSORIA,0) ACESSORIA,
		ISNULL(I.DSCREQ,0) DSCREQ,
		R.NFEDWS 

	FROM REQNFC R
		LEFT JOIN CLIENTES C ON (C.CODCLI=R.CODCLI)
		LEFT JOIN ITEMNFC I ON (I.SID=R.SID)

	WHERE ((LEN(R.NUMNOT)>0) OR (LEN(R.NUMNCF)>0))
		AND (R.DATSAI >= '01-MAY-2025')
		AND (R.DATSAI <= '06-MAY-2025')
		AND (R.TIPONF  = 'I')

	union all

	SELECT
		CASE WHEN R.NFERWS='110' THEN 'Denegada'  WHEN R.NFERWS='102' THEN 'Inutilizada' ELSE 'Cancelada' END as Sit,
		 CASE WHEN substring(R.CFOP,1,1) IN ('1','2','3') THEN 'E' ELSE 'S' END AS ENTSAI,
		' ' AS COD_NOTA,
		' ' AS MVA,
		' ' AS COD_IBGE,
		R.DATEMI,
		R.DATSAI,
		R.NUMREQ, 
		R.TIPOREQ,
		 CASE WHEN isnull(LEN(R.CFEID),0)<>0 AND isnull(LEN(R.NFEID),0)= 0 THEN substring(R.CFEID,21,2)
		WHEN isnull(LEN(R.CFEID),0)<>0 AND isnull(LEN(R.NFEID),0)<>0 THEN substring(R.NFEID,21,2)
		WHEN isnull(LEN(R.NFEID),0)<>0 AND isnull(LEN(R.CFEID),0)= 0 THEN substring(R.NFEID,21,2) ELSE R.MODNF END AS Mod,
		CASE WHEN isnull(LEN(R.CFEID),0)<>0 THEN R.CFESTA ELSE R.NFERWS END AS STA,
		R.NFERWS,
		R.CFESTA,
		R.NUMNOT,
		R.NUMNCF,
		CASE WHEN isnull(LEN(R.CFEID),0)<>0 AND isnull(LEN(R.NFEID),0)=0 THEN R.CFEID ELSE R.NFEID END  AS Chave,
		R.NFEPRO,
		R.CODCLI,
		C.NOME,
		C.ENDERECO+', '+C.NUMERO AS ENDER,
		C.BAIRRO,
		C.CIDADE,
		C.UF,
		R.CPFCNPJ,
		R.PESSOA,
		R.TOTGERAL,
		I.SEQIT,
		I.CODSTK,
		I.CODFAB,
		I.CODEAN,
		I.NOME    AS Produto,
		I.CODIPI,
		I.CFOP,
		I.UNIDADE,
		I.QTDADE,
		I.PRCLIQ,
		I.TOTLIQ,
		I.PRCCTB,
		I.CODCST,
		I.ALQICM,
		I.VLRICM,
		I.PRCCTB AS BICMSST,
		I.ALQSBT,
		I.VLRRET,
		I.CSTPIS,
		I.ALQPIS,
		I.VLRPIS,
		I.CSTCOF,
		I.ALQCOF,
		I.VLRCOF,
		I.ALQIPI,
		I.VLRIPI,
		CASE WHEN LEN(LTRIM(ISNULL(R.Portal,''))) = 0 THEN 'Loja' ELSE R.PORTAL END AS Portal,
		R.Prisma,
		CASE WHEN I.TIPOSTK='S' THEN R.NUMNFS ELSE NULL END AS NUMNFS,
		CASE WHEN I.TIPOSTK='S' THEN R.TOTSRV ELSE NULL END AS TOTSRV,
		CASE WHEN I.TIPOSTK='S' THEN R.NFSPRO ELSE NULL END AS NFSPRO,
		ISNULL(I.PRCDAI,0) BSTFCP,
		ISNULL(I.ALQFCP,0) ALQFCP,
		ISNULL(I.VLRFCP,0) VSTFCP,
		ISNULL(I.BICENT,0) BICENT,
		ISNULL(I.AICENT,0) AICENT,
		ISNULL(I.VICENT,0) VICENT,
		ISNULL(I.BSTENT,0) BSTENT,
		ISNULL(I.ALQSBT,0) ALQSBT2,
		ISNULL(I.VSTENT,0) VSTENT,
		ISNULL(I.FRETE,0) FRETE,
		ISNULL(I.SEGURO,0) SEGURO,
		ISNULL(I.ACESSORIA,0) ACESSORIA,
		ISNULL(I.DSCREQ,0) DSCREQ,
		R.NFEDWS 

	FROM REGRQA R
		LEFT JOIN CLIENTES C ON(C.CODCLI=R.CODCLI)
		LEFT JOIN REGIRA I ON(I.SID   =R.SID)
		
	WHERE (((LEN(R.NUMNOT)>0) OR (LEN(R.NUMNCF)>0)) OR R.NUMREQ LIKE'%NFE-INU%')
		AND ('S' = 'S')
		AND (R.DATSAI >= '01-MAY-2025')
		AND (R.DATSAI <= '06-MAY-2025')
		AND (R.TIPONF  = 'I')
		) AS REL
WHERE(1=1)
	AND (REL.ENTSAI = 'S')
	AND (REL.MOD IN ('55', '59') )

ORDER BY REL.NUMNOT,REL.SEQIT

