SELECT
	VD.NUMREQ,
	VD.NUMNOT,
	VD.DATEMI,
	VD.NFEDWS,
	VD.DTHCAD AS Venda,
	VD.CODCLI+'-'+CL.FANTASIA AS Cliente,
	VD.CODVEN+'-'+VN.FANTASIA AS Vendedor,
	IV.CODSTK AS Codigo,
	IV.CodFab,
	IV.NOME   AS Produto,
	IV.Marca,
	SP.CODSEP+'-'+SE.FANTASIA AS Separador,
	SP.DTHCAD AS ISep,
	(CASE WHEN SP.[STATUS]='F' THEN SP.DTHUPD ELSE NULL END) AS FSep,
	(CASE WHEN SP.[STATUS]='F' THEN SP.DTHUPD ELSE NULL END)-SP.DTHCAD AS Tsep,
	CF.CODEXP+'-'+CO.FANTASIA AS Conferente,
	CF.DTHCAD AS IConf,
	(CASE WHEN CF.[STATUS]='F' THEN CF.DTHUPD ELSE NULL END) AS FConf,
	(CASE WHEN CF.[STATUS]='F' THEN CF.DTHUPD ELSE NULL END)-CF.DTHCAD AS Tconf,
	(CASE WHEN CF.[STATUS]='F' THEN CF.DTHUPD ELSE NULL END)-VD.DTHCAD AS Tvd_Cnf,
	EN.CODTRP+'-'+MT.FANTASIA AS MotoBoy,
	EN.DATSAI AS Entrega,
	EN.DATRET AS Retorno,
	EN.DATRET-EN.DATSAI AS Tent,
	LO.Piso
	
FROM REQVDA AS VD
	LEFT JOIN ITEMVDA AS IV ON (IV.SID=VD.SID)
	LEFT JOIN CLIENTES AS VN ON (VN.CODCLI=VD.CODVEN)
	LEFT JOIN CLIENTES AS CL ON (CL.CODCLI=VD.CODCLI)
	LEFT JOIN LOCALSTK AS LO ON (LO.CODLOC = IV.CODLOC)
	LEFT JOIN ITEMSEP AS SP ON (SP.MARCA=VD.SID) AND (SP.CODSTK='SEP') AND (SP.PISO = LO.PISO)
	LEFT JOIN CLIENTES AS SE ON (SE.CODCLI=SP.CODSEP)
	LEFT JOIN ITEMSEP AS CF ON (CF.MARCA=VD.SID)AND(CF.CODSTK='CNF')
	LEFT JOIN CLIENTES AS CO ON (CO.CODCLI=CF.CODEXP)
	LEFT JOIN REQCRE AS EN ON (EN.SIDREQ=VD.SID)
	LEFT JOIN CLIENTES AS MT ON (MT.CODCLI=EN.CODTRP)
	
WHERE (VD.TIPOREQ IN ('VD','TS'))
	AND (VD.DATEMI >= '2024-09-01')
	AND (VD.DATEMI <= '2024-09-10')
ORDER BY VD.DTHCAD
