WITH DADOS AS (
SELECT 
  DISTINCT
  CONVERT(VARCHAR(20),R.DTHCAD,103) AS LANC,
  R.DATEMI                 AS EMISSAO,
  RQ.COMPRADOR             AS Comprador,
  R.CODCLI+' - '+C.NOME    AS Fornecedor,
  TIT.DATVEN               AS Vencimento,
  R.NUMNOT,
  R.NFEID,
  RQ.TIPOREQ               AS TR,
  RQ.NUMREQ                AS REQ,
  RQ.DTHCAD                AS EMI_PNRC,
  RQ.PESOBRU,
  RQ.PESOLIQ,
  RQ.Volumes,
  R.STACOM                 AS Compras,
  R.STAFIS                 AS Fiscal,
  R.STACNF                 AS Conf,
  R.DATENT                 AS Recebimento,
  R.NOMREC                 AS Responsavel,
  R.NOMMOT                 AS Motorista,
  R.OBSREC                 AS Observacao,
  R.CODCOM +' - '+COM.NOME AS 'Resp.Compras',
  HCOM.DTHUPD              AS Hora_Compras,
  R.CODFIS +' - '+FIS.NOME AS 'Resp. Fiscal',
  HFIS.DTHUPD              AS Hora_Fiscal,                  
  R.CODCNF +' - '+CNF.NOME AS 'Resp. Conferente',
  HCNF.DTHUPD              AS Hora_Conferencia ,
  CITENS.CONTADOR

FROM JACSYSDB.DBO.ITEMNXP R
  LEFT JOIN JACSYSDB.DBO.CLIENTES C ON(C.CODCLI=R.CODCLI)
  LEFT JOIN JACSYSDB.DBO.ITEMSTK  S ON(S.CODSTK=R.CODSTK)
  LEFT JOIN JACSYSDB.DBO.JACUSR   CNF ON(CNF.CODUSR=R.CODCNF) 
  LEFT JOIN JACSYSDB.DBO.JACUSR   COM ON(COM.CODUSR=R.CODCOM) 
  LEFT JOIN JACSYSDB.DBO.JACUSR   FIS ON(FIS.CODUSR=R.CODFIS) 
  LEFT JOIN JACSYSDB.DBO.ITEMNXP  HCOM ON(HCOM.SEQIT='COM') AND(HCOM.NFEID=R.NFEID) AND(LTRIM(SUBSTRING(HCOM.SID,3,30))=R.SID) 
  LEFT JOIN JACSYSDB.DBO.ITEMNXP  HFIS ON(HFIS.SEQIT='FIS') AND(HFIS.NFEID=R.NFEID) AND(LTRIM(SUBSTRING(HFIS.SID,3,30))=R.SID)
  LEFT JOIN JACSYSDB.DBO.ITEMNXP  HCNF ON(HCNF.SEQIT='CNF') AND(HCNF.NFEID=R.NFEID) AND(LTRIM(SUBSTRING(HCNF.SID,3,30))=R.SID)                       

  OUTER APPLY (
    SELECT TOP 1 P.CODVEN+'-'+ISNULL(VEN.NOME,'') AS COMPRADOR,P.NUMNOT,P.TIPOREQ,P.DTHCAD,P.NUMREQ,
     P.PESOBRU,P.PESOLIQ,P.VOLUMES
     FROM JACSYSDB.DBO.REQCOM P LEFT JOIN JACSYSDB.DBO.CLIENTES VEN ON(VEN.CODCLI=P.CODVEN) 
     WHERE (P.NFEID=R.NFEID)) AS RQ

  OUTER APPLY (SELECT TOP 1 T.DATVEN FROM JACSYSDB.DBO.TITULOS T WHERE T.NUMREQ=RQ.NUMREQ ORDER BY T.DATVEN desc) AS TIT

  OUTER APPLY (SELECT COUNT(DISTINCT(CODSTK)) CONTADOR FROM JACSYSDB.DBO.ITEMNXP I WHERE (I.NUMNOT=R.NUMNOT) AND (I.NFEID=R.NFEID)) AS CITENS

WHERE (R.NFEID>'') AND (R.SEQIT='001')
)
SELECT D.*,
 N.SEQIT,N.CODSTK,N.CODFAB,N.CODEAN,N.NOME,N.UNIDADE,N.CFOP,N.QTDADE,N.PRECO,N.TOTAL
FROM DADOS D
LEFT JOIN JACSYSDB.DBO.ITEMNXP N ON (N.NFEID=D.NFEID)
WHERE (N.CODSTK <> '<NFE>')
